version: '3.4'

services:
    jupyter-lab:
        build:
            context: ./python-jupyterlab
            dockerfile: Dockerfile
        # environment:
        ports:
        - "8888:8888"
        tty: true
        command:
            jupyter lab 
                --ip=0.0.0.0
                --allow-root
                --no-browser
                --NotebookApp.token=''
                --NotebookApp.notebook_dir='/home/project'
        volumes:
            - ./python-project:/home/project
